# Generated by Django 4.2.19 on 2025-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo", models.TextField()),
                ("todo_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField()),
                ("finish_date", models.DateTimeField()),
                ("statu", models.BooleanField()),
            ],
        ),
    ]
