# Generated by Django 4.2.19 on 2025-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="finish_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="statu",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="todo",
            field=models.CharField(max_length=200),
        ),
    ]
