# Generated by Django 4.2.19 on 2025-02-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_todolist_finish_date_alter_todolist_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="finish_date",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="start_date",
        ),
    ]
