# Generated by Django 4.2.19 on 2025-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_todolist_finish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="todo_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
