# Generated by Django 4.2.19 on 2025-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_todolist_todo_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="commence",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="todolist",
            name="fin",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="todo_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
