# Generated by Django 4.2.19 on 2025-02-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_todolist_commence_todolist_fin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="commence",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="fin",
            field=models.DateField(null=True),
        ),
    ]
