# Generated by Django 5.1.6 on 2025-02-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemodel",
            name="images",
        ),
    ]
