# Generated by Django 5.1.6 on 2025-02-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_articlemodel_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemodel",
            name="author",
        ),
    ]
