# Generated by Django 5.1.6 on 2025-02-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_articles_delete_articlemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Articles",
        ),
    ]
