# Generated by Django 5.1.6 on 2025-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images"),
        ),
    ]
