# Generated by Django 5.1.6 on 2025-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
